version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: quiz_moba_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chocolate1122
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  quiz-app:
    build: .
    container_name: quiz-app
    ports:
      - "8082:8080"
      - "5005:5005"
    depends_on:
      - postgres
    environment:
      ENV_FILE: digital-ocean-remote
      ENV_PATH: /app/env
      USE_ENV_FOLDER_PROFILE_ENVIRONMENTS: true
    env_file:
      - ./env/digital-ocean-remote.env

