version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  flyway:
    image: flyway/flyway
    container_name: flyway
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      FLYWAY_SCHEMAS: ${FLYWAY_SCHEMAS}
      FLYWAY_BASELINE_ON_MIGRATE: ${FLYWAY_BASELINE_ON_MIGRATE}
      FLYWAY_VALIDATE_ON_MIGRATE: ${FLYWAY_VALIDATE_ON_MIGRATE}
      FLYWAY_VALIDATE_MIGRATION_NAMING: ${FLYWAY_VALIDATE_MIGRATION_NAMING}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

  quiz-app:
    build: .
    container_name: advanced-quiz-app
    ports:
      - "8082:8080"
      - "5005:5005"
    depends_on:
      - postgres
      - flyway
    env_file:
      - ./src:/app/src/main/resources/env/digital-ocean-remote.env
    volumes:
      - ./src:/app/src
